# Amazon Reviews

## Imports & Readings

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

#os.getcwd()

'/Users/paulbojan/Documents/TU Wien/2.Semester/Machine Learning/assignments/ex1/local/datasets'

In [9]:
amazon_train = pd.read_csv('test_amazon_review.csv')
amazon_test = pd.read_csv('train_amazon_review.csv')

In [11]:
display(amazon_train)
amazon_train.shape

,ID,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V9991,V9992,V9993,V9994,V9995,V9996,V9997,V9998,V9999,V10000
0,750,23,6,4,7,11,0,5,2,6,...,0,0,1,0,0,0,0,0,0,0
1,751,20,12,15,6,9,14,2,6,2,...,1,3,0,0,0,0,0,0,0,0
2,752,13,10,10,5,12,5,3,4,5,...,1,0,1,0,0,0,1,0,1,1
3,753,14,15,6,1,7,2,7,2,5,...,0,0,1,2,0,2,1,0,1,0
4,754,9,8,3,4,10,3,2,2,1,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
745,1495,7,5,3,7,0,4,0,3,2,...,0,0,0,0,0,0,0,0,0,0
746,1496,13,5,4,3,2,5,1,2,5,...,0,0,0,0,0,0,0,0,0,0
747,1497,6,8,9,7,15,2,5,2,3,...,0,0,0,0,0,0,0,0,0,0
748,1498,20,12,9,11,7,8,2,2,5,...,0,0,0,0,0,0,0,0,0,0
749,1499,6,2,3,2,4,3,4,1,2,...,1,0,0,1,0,0,0,0,0,0

(750, 10001)

In [ ]:
DataFrame.pivot